export const originaltimezones = [
	{
		data: "GMT -12:00",
		label: "GMT -12:00",
		value: -720,
	},
	{
		data: "GMT -11:00",
		label: "GMT -11:00",
		value: -660,
	},
	{
		data: "GMT -10:00",
		label: "GMT -10:00",
		value: -600,
	},
	{
		data: "GMT -9:00",
		label: "GMT -9:00",
		value: -540,
	},
	{
		data: "GMT -8:00",
		label: "GMT -8:00",
		value: -480,
	},
	{
		data: "GMT -7:00",
		label: "GMT -7:00",
		value: -420,
	},
	{
		data: "GMT -6:00",
		label: "GMT -6:00",
		value: -360,
	},
	{
		data: "GMT -5:00",
		label: "GMT -5:00",
		value: -300,
	},
	{
		data: "GMT -4:00",
		label: "GMT -4:00",
		value: -240,
	},
	{
		data: "GMT -3:00",
		label: "GMT -3:00",
		value: -180,
	},
	{
		data: "GMT -2:00",
		label: "GMT -2:00",
		value: -120,
	},
	{
		data: "GMT -1:00",
		label: "GMT -1:00",
		value: -60,
	},
	{
		data: "GMT +0:00",
		label: "GMT +0:00",
		value: 0,
	},
	{
		data: "GMT +1:00",
		label: "GMT +1:00",
		value: 60,
	},
	{
		data: "GMT +2:00",
		label: "GMT +2:00",
		value: 120,
	},
	{
		data: "GMT +3:00",
		label: "GMT +3:00",
		value: 180,
	},
	{
		data: "GMT +4:00",
		label: "GMT +4:00",
		value: 240,
	},
	{
		data: "GMT +5:00",
		label: "GMT +5:00",
		value: 300,
	},
	{
		data: "GMT +6:00",
		label: "GMT +6:00",
		value: 360,
	},
	{
		data: "GMT +7:00",
		label: "GMT +7:00",
		value: 420,
	},
	{
		data: "GMT +8:00",
		label: "GMT +8:00",
		value: 480,
	},
	{
		data: "GMT +9:00",
		label: "GMT +9:00",
		value: 540,
	},
	{
		data: "GMT +10:00",
		label: "GMT +10:00",
		value: 600,
	},
	{
		data: "GMT +11:00",
		label: "GMT +11:00",
		value: 660,
	},
	{
		data: "GMT +12:00",
		label: "GMT +12:00",
		value: 720,
	},
];

export const timezones = [
	{
		value: "Samoa Standard Time",
		label: "Midway Island, Samoa",
		offset: -11,
		abbrev: "SST",
		altName: "Samoa Standard Time",
		gmtPrefix: "(GMT-11:00)",
	},
	{
		value: "Hawaii-Aleutian Standard Time",
		label: "Hawaii",
		offset: -9,
		abbrev: "HAST",
		altName: "Hawaii-Aleutian Standard Time",
		gmtPrefix: "(GMT-9:00)",
	},
	{
		value: "Alaska Standard Time",
		label: "Alaska",
		offset: -9,
		abbrev: "AKST",
		altName: "Alaska Standard Time",
		gmtPrefix: "(GMT-9:00)",
	},
	{
		value: "Pacific Standard Time",
		label: "Tijuana",
		offset: -8,
		abbrev: "PST",
		altName: "Pacific Standard Time",
		gmtPrefix: "(GMT-8:00)",
	},
	{
		value: "Pacific Standard Time",
		label: "Pacific Time",
		offset: -8,
		abbrev: "PST",
		altName: "Pacific Standard Time",
		gmtPrefix: "(GMT-8:00)",
	},
	{
		value: "Mountain Standard Time",
		label: "Mountain Time",
		offset: -7,
		abbrev: "MST",
		altName: "Mountain Standard Time",
		gmtPrefix: "(GMT-7:00)",
	},
	{
		value: "Mountain Standard Time",
		label: "Dawson, Yukon",
		offset: -7,
		abbrev: "MST",
		altName: "Mountain Standard Time",
		gmtPrefix: "(GMT-7:00)",
	},
	{
		value: "Mexican Pacific Standard Time",
		label: "Chihuahua, La Paz, Mazatlan",
		offset: -7,
		abbrev: "HNPMX",
		altName: "Mexican Pacific Standard Time",
		gmtPrefix: "(GMT-7:00)",
	},
	{
		value: "Mountain Standard Time",
		label: "Arizona",
		offset: -7,
		abbrev: "MST",
		altName: "Mountain Standard Time",
		gmtPrefix: "(GMT-7:00)",
	},
	{
		value: "Central Standard Time",
		label: "Central Time",
		offset: -6,
		abbrev: "CST",
		altName: "Central Standard Time",
		gmtPrefix: "(GMT-6:00)",
	},
	{
		value: "Central Standard Time",
		label: "Saskatchewan",
		offset: -6,
		abbrev: "CST",
		altName: "Central Standard Time",
		gmtPrefix: "(GMT-6:00)",
	},
	{
		value: "Central Mexico Standard Time",
		label: "Guadalajara, Mexico City, Monterrey",
		offset: -6,
		abbrev: "CST",
		altName: "Central Mexico Standard Time",
		gmtPrefix: "(GMT-6:00)",
	},
	{
		value: "Central Standard Time",
		label: "Central America",
		offset: -6,
		abbrev: "CST",
		altName: "Central Standard Time",
		gmtPrefix: "(GMT-6:00)",
	},
	{
		value: "Eastern Standard Time",
		label: "Eastern Time",
		offset: -5,
		abbrev: "EST",
		altName: "Eastern Standard Time",
		gmtPrefix: "(GMT-5:00)",
	},
	{
		value: "Colombia Standard Time",
		label: "Bogota, Lima, Quito",
		offset: -5,
		abbrev: "COT",
		altName: "Colombia Standard Time",
		gmtPrefix: "(GMT-5:00)",
	},
	{
		value: "Venezuela Standard Time",
		label: "Caracas, La Paz",
		offset: -4,
		abbrev: "VET",
		altName: "Venezuela Standard Time",
		gmtPrefix: "(GMT-4:00)",
	},
	{
		value: "Newfoundland Standard Time",
		label: "Newfoundland and Labrador",
		offset: -3.5,
		abbrev: "HNTN",
		altName: "Newfoundland Standard Time",
		gmtPrefix: "(GMT-3:30)",
	},
	{
		value: "Chile Standard Time",
		label: "Santiago",
		offset: -3,
		abbrev: "CLT",
		altName: "Chile Standard Time",
		gmtPrefix: "(GMT-3:00)",
	},
	{
		value: "Brasilia Standard Time",
		label: "Brasilia",
		offset: -3,
		abbrev: "BRT",
		altName: "Brasilia Standard Time",
		gmtPrefix: "(GMT-3:00)",
	},
	{
		value: "Uruguay Standard Time",
		label: "Montevideo",
		offset: -3,
		abbrev: "UYT",
		altName: "Uruguay Standard Time",
		gmtPrefix: "(GMT-3:00)",
	},
	{
		value: "Argentina Standard Time",
		label: "Buenos Aires, Georgetown",
		offset: -3,
		abbrev: "ART",
		altName: "Argentina Standard Time",
		gmtPrefix: "(GMT-3:00)",
	},
	{
		value: "West Greenland Standard Time",
		label: "Greenland",
		offset: -3,
		abbrev: "WGT",
		altName: "West Greenland Standard Time",
		gmtPrefix: "(GMT-3:00)",
	},
	{
		value: "Azores Standard Time",
		label: "Azores",
		offset: -1,
		abbrev: "AZOT",
		altName: "Azores Standard Time",
		gmtPrefix: "(GMT-1:00)",
	},
	{
		value: "Cape Verde Standard Time",
		label: "Cape Verde Islands",
		offset: -1,
		abbrev: "CVT",
		altName: "Cape Verde Standard Time",
		gmtPrefix: "(GMT-1:00)",
	},
	{
		value: "British Standard Time",
		label: "UTC",
		offset: 0,
		abbrev: "GMT",
		altName: "British Standard Time",
		gmtPrefix: "(GMT+0:00)",
	},
	{
		value: "British Standard Time",
		label: "Edinburgh, London",
		offset: 0,
		abbrev: "GMT",
		altName: "British Standard Time",
		gmtPrefix: "(GMT+0:00)",
	},
	{
		value: "Irish Standard Time",
		label: "Dublin",
		offset: 0,
		abbrev: "GMT",
		altName: "Irish Standard Time",
		gmtPrefix: "(GMT+0:00)",
	},
	{
		value: "Western European Standard Time",
		label: "Lisbon",
		offset: 0,
		abbrev: "WET",
		altName: "Western European Standard Time",
		gmtPrefix: "(GMT+0:00)",
	},
	{
		value: "Western European Standard Time",
		label: "Canary Islands",
		offset: 0,
		abbrev: "WET",
		altName: "Western European Standard Time",
		gmtPrefix: "(GMT+0:00)",
	},
	{
		value: "Morocco Standard Standard Time",
		label: "Casablanca, Monrovia",
		offset: 1,
		abbrev: "WET",
		altName: "Morocco Standard Standard Time",
		gmtPrefix: "(GMT+1:00)",
	},
	{
		value: "Central European Standard Time",
		label: "Belgrade, Bratislava, Budapest, Ljubljana, Prague",
		offset: 1,
		abbrev: "CET",
		altName: "Central European Standard Time",
		gmtPrefix: "(GMT+1:00)",
	},
	{
		value: "Central European Standard Time",
		label: "Sarajevo, Skopje, Warsaw, Zagreb",
		offset: 1,
		abbrev: "CET",
		altName: "Central European Standard Time",
		gmtPrefix: "(GMT+1:00)",
	},
	{
		value: "Central European Standard Time",
		label: "Brussels, Copenhagen, Madrid, Paris",
		offset: 1,
		abbrev: "CET",
		altName: "Central European Standard Time",
		gmtPrefix: "(GMT+1:00)",
	},
	{
		value: "Central European Standard Time",
		label: "Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
		offset: 1,
		abbrev: "CET",
		altName: "Central European Standard Time",
		gmtPrefix: "(GMT+1:00)",
	},
	{
		value: "Central European Standard Time",
		label: "West Central Africa",
		offset: 1,
		abbrev: "CET",
		altName: "Central European Standard Time",
		gmtPrefix: "(GMT+1:00)",
	},
	{
		value: "Eastern European Standard Time",
		label: "Bucharest",
		offset: 2,
		abbrev: "EET",
		altName: "Eastern European Standard Time",
		gmtPrefix: "(GMT+2:00)",
	},
	{
		value: "Eastern European Standard Time",
		label: "Cairo",
		offset: 2,
		abbrev: "EET",
		altName: "Eastern European Standard Time",
		gmtPrefix: "(GMT+2:00)",
	},
	{
		value: "Eastern European Standard Time",
		label: "Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
		offset: 2,
		abbrev: "EET",
		altName: "Eastern European Standard Time",
		gmtPrefix: "(GMT+2:00)",
	},
	{
		value: "Eastern European Standard Time",
		label: "Athens",
		offset: 2,
		abbrev: "EET",
		altName: "Eastern European Standard Time",
		gmtPrefix: "(GMT+2:00)",
	},
	{
		value: "Israel Standard Time",
		label: "Jerusalem",
		offset: 2,
		abbrev: "IST",
		altName: "Israel Standard Time",
		gmtPrefix: "(GMT+2:00)",
	},
	{
		value: "Central Africa Standard Time",
		label: "Harare, Pretoria",
		offset: 2,
		abbrev: "CAT",
		altName: "Central Africa Standard Time",
		gmtPrefix: "(GMT+2:00)",
	},
	{
		value: "Moscow Standard Time",
		label: "Istanbul, Minsk, Moscow, St. Petersburg, Volgograd",
		offset: 3,
		abbrev: "MSK",
		altName: "Moscow Standard Time",
		gmtPrefix: "(GMT+3:00)",
	},
	{
		value: "Arabian Standard Time",
		label: "Kuwait, Riyadh",
		offset: 3,
		abbrev: "AST",
		altName: "Arabian Standard Time",
		gmtPrefix: "(GMT+3:00)",
	},
	{
		value: "East Africa Standard Time",
		label: "Nairobi",
		offset: 3,
		abbrev: "EAT",
		altName: "East Africa Standard Time",
		gmtPrefix: "(GMT+3:00)",
	},
	{
		value: "Arabian Standard Time",
		label: "Baghdad",
		offset: 3,
		abbrev: "AST",
		altName: "Arabian Standard Time",
		gmtPrefix: "(GMT+3:00)",
	},
	{
		value: "Iran Standard Time",
		label: "Tehran",
		offset: 3.5,
		abbrev: "IRST",
		altName: "Iran Standard Time",
		gmtPrefix: "(GMT+3:30)",
	},
	{
		value: "Gulf Standard Time",
		label: "Abu Dhabi, Muscat",
		offset: 4,
		abbrev: "GST",
		altName: "Gulf Standard Time",
		gmtPrefix: "(GMT+4:00)",
	},
	{
		value: "Azerbaijan Standard Time",
		label: "Baku, Tbilisi, Yerevan",
		offset: 4,
		abbrev: "AZT",
		altName: "Azerbaijan Standard Time",
		gmtPrefix: "(GMT+4:00)",
	},
	{
		value: "Afghanistan Standard Time",
		label: "Kabul",
		offset: 4.5,
		abbrev: "AFT",
		altName: "Afghanistan Standard Time",
		gmtPrefix: "(GMT+4:30)",
	},
	{
		value: "Yekaterinburg Standard Time",
		label: "Ekaterinburg",
		offset: 5,
		abbrev: "YEKT",
		altName: "Yekaterinburg Standard Time",
		gmtPrefix: "(GMT+5:00)",
	},
	{
		value: "Pakistan Standard Time",
		label: "Islamabad, Karachi, Tashkent",
		offset: 5,
		abbrev: "PKT",
		altName: "Pakistan Standard Time",
		gmtPrefix: "(GMT+5:00)",
	},
	{
		value: "India Standard Time",
		label: "Chennai, Kolkata, Mumbai, New Delhi",
		offset: 5.5,
		abbrev: "IST",
		altName: "India Standard Time",
		gmtPrefix: "(GMT+5:30)",
	},
	{
		value: "India Standard Time",
		label: "Sri Jayawardenepura",
		offset: 5.5,
		abbrev: "IST",
		altName: "India Standard Time",
		gmtPrefix: "(GMT+5:30)",
	},
	{
		value: "Nepal Standard Time",
		label: "Kathmandu",
		offset: 5.75,
		abbrev: "NPT",
		altName: "Nepal Standard Time",
		gmtPrefix: "(GMT+5:45)",
	},
	{
		value: "Bangladesh Standard Time",
		label: "Astana, Dhaka",
		offset: 6,
		abbrev: "BST",
		altName: "Bangladesh Standard Time",
		gmtPrefix: "(GMT+6:00)",
	},
	{
		value: "East Kazakhstan Standard Time",
		label: "Almaty, Novosibirsk",
		offset: 6,
		abbrev: "ALMT",
		altName: "East Kazakhstan Standard Time",
		gmtPrefix: "(GMT+6:00)",
	},
	{
		value: "Myanmar Standard Time",
		label: "Yangon Rangoon",
		offset: 6.5,
		abbrev: "MMT",
		altName: "Myanmar Standard Time",
		gmtPrefix: "(GMT+6:30)",
	},
	{
		value: "Indochina Standard Time",
		label: "Bangkok, Hanoi, Jakarta",
		offset: 7,
		abbrev: "ICT",
		altName: "Indochina Standard Time",
		gmtPrefix: "(GMT+7:00)",
	},
	{
		value: "Krasnoyarsk Standard Time",
		label: "Krasnoyarsk",
		offset: 7,
		abbrev: "KRAT",
		altName: "Krasnoyarsk Standard Time",
		gmtPrefix: "(GMT+7:00)",
	},
	{
		value: "China Standard Time",
		label: "Beijing, Chongqing, Hong Kong SAR, Urumqi",
		offset: 8,
		abbrev: "CST",
		altName: "China Standard Time",
		gmtPrefix: "(GMT+8:00)",
	},
	{
		value: "Malaysia Standard Time",
		label: "Kuala Lumpur, Singapore",
		offset: 8,
		abbrev: "MYT",
		altName: "Malaysia Standard Time",
		gmtPrefix: "(GMT+8:00)",
	},
	{
		value: "Taipei Standard Time",
		label: "Taipei",
		offset: 8,
		abbrev: "CST",
		altName: "Taipei Standard Time",
		gmtPrefix: "(GMT+8:00)",
	},
	{
		value: "Western Australia Standard Time",
		label: "Perth",
		offset: 8,
		abbrev: "AWST",
		altName: "Western Australia Standard Time",
		gmtPrefix: "(GMT+8:00)",
	},
	{
		value: "Irkutsk Standard Time",
		label: "Irkutsk, Ulaanbaatar",
		offset: 8,
		abbrev: "IRKT",
		altName: "Irkutsk Standard Time",
		gmtPrefix: "(GMT+8:00)",
	},
	{
		value: "Korean Standard Time",
		label: "Seoul",
		offset: 9,
		abbrev: "KST",
		altName: "Korean Standard Time",
		gmtPrefix: "(GMT+9:00)",
	},
	{
		value: "Japan Standard Time",
		label: "Osaka, Sapporo, Tokyo",
		offset: 9,
		abbrev: "JST",
		altName: "Japan Standard Time",
		gmtPrefix: "(GMT+9:00)",
	},
	{
		value: "Yakutsk Standard Time",
		label: "Yakutsk",
		offset: 9,
		abbrev: "YAKT",
		altName: "Yakutsk Standard Time",
		gmtPrefix: "(GMT+9:00)",
	},
	{
		value: "Australian Central Standard Time",
		label: "Darwin",
		offset: 9.5,
		abbrev: "ACST",
		altName: "Australian Central Standard Time",
		gmtPrefix: "(GMT+9:30)",
	},
	{
		value: "Central Australia Standard Time",
		label: "Adelaide",
		offset: 9.5,
		abbrev: "ACST",
		altName: "Central Australia Standard Time",
		gmtPrefix: "(GMT+9:30)",
	},
	{
		value: "Eastern Australia Standard Time",
		label: "Canberra, Melbourne, Sydney",
		offset: 10,
		abbrev: "AEST",
		altName: "Eastern Australia Standard Time",
		gmtPrefix: "(GMT+10:00)",
	},
	{
		value: "Brisbane Standard Time",
		label: "Brisbane",
		offset: 10,
		abbrev: "AEST",
		altName: "Brisbane Standard Time",
		gmtPrefix: "(GMT+10:00)",
	},
	{
		value: "Eastern Australia Standard Time",
		label: "Hobart",
		offset: 10,
		abbrev: "AEST",
		altName: "Eastern Australia Standard Time",
		gmtPrefix: "(GMT+10:00)",
	},
	{
		value: "Vladivostok Standard Time",
		label: "Vladivostok",
		offset: 10,
		abbrev: "VLAT",
		altName: "Vladivostok Standard Time",
		gmtPrefix: "(GMT+10:00)",
	},
	{
		value: "Chamorro Standard Time",
		label: "Guam, Port Moresby",
		offset: 10,
		abbrev: "ChST",
		altName: "Chamorro Standard Time",
		gmtPrefix: "(GMT+10:00)",
	},
	{
		value: "Magadan Standard Time",
		label: "Magadan, Solomon Islands, New Caledonia",
		offset: 11,
		abbrev: "MAGT",
		altName: "Magadan Standard Time",
		gmtPrefix: "(GMT+11:00)",
	},
	{
		value: "Petropavlovsk-Kamchatski Standard Time",
		label: "Kamchatka, Marshall Islands",
		offset: 12,
		abbrev: "PETT",
		altName: "Petropavlovsk-Kamchatski Standard Time",
		gmtPrefix: "(GMT+12:00)",
	},
	{
		value: "Fiji Standard Time",
		label: "Fiji Islands",
		offset: 12,
		abbrev: "FJT",
		altName: "Fiji Standard Time",
		gmtPrefix: "(GMT+12:00)",
	},
	{
		value: "New Zealand Standard Time",
		label: "Auckland, Wellington",
		offset: 12,
		abbrev: "NZST",
		altName: "New Zealand Standard Time",
		gmtPrefix: "(GMT+12:00)",
	},
	{
		value: "Tonga Standard Time",
		label: "Nuku'alofa",
		offset: 13,
		abbrev: "TOT",
		altName: "Tonga Standard Time",
		gmtPrefix: "(GMT+13:00)",
	},
];
